version: '3'
networks:
  development:
volumes:
  db_data:
  gem_cache:
  shared_data:
services:
  bibliobase_redis:
    image: redis:4.0-alpine
    command: redis-server
    networks:
      - development
    volumes:
      - shared_data:/var/shared/redis
  bibliobase_db:
    image: postgres:12.5-alpine
    container_name: bibliobase_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  bibliobase_app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: bibliobase_app
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    env_file: docker/.development.env
    entrypoint: dev-entrypoint.sh
    command: ['bundle', 'exec', 'rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    environment:
      RAILS_ENV: development
    depends_on:
      - bibliobase_db
